### ISSUE TITLE
"Unfortunately, Firefox has stopped."

### ISSUE THREAD

**Issue by polyzen** [copperhead/bugtracker#105]
[logcat](https://ptpb.pw/PcYX)

**Comment by vanitasvitae** [comment]
Same for Orfox.

**Comment by thestinger** [comment]
That's strange. It appears to be the same GeckoLinker issues as before but the workaround is still in place.

**Comment by thestinger** [comment]
12-20 11:24:25.586  7325  7340 D GeckoLoader: Gecko environment env0: null

**Comment by thestinger** [comment]
Looks like the environment variables aren't being passed along. I can't look into it right now but that's probably the problem (if anyone wants to fiddle with platform_frameworks_base).

**Comment by vanitasvitae** [comment]
I found that nearly all apps that display html content (All browsers, K9 Mail, apps that use WebView) are not working for me. Has that to do with #96?

**Comment by thestinger** [comment]
No, nothing to do with that. I don't know what's wrong and am working on it. I think there's more than one issue and the Firefox stuff isn't related.

**Comment by thestinger** [comment]
Issues like this are bottlenecked by build time. Need better hardware to get through this stuff faster. I've been building all day.

**Comment by thestinger** [comment]
I think I've narrowed down the issue in non-Firefox browsers to the set of recent Bionic commits. I'm not entirely sure yet and it needs to be narrowed down to a specific one. I'm still working on narrowing down the cause of the Firefox issue. Just need to keep reverting / unreverting changes and building again until the cause is known.

**Comment by thestinger** [comment]
The Firefox issue is at least narrowed down to either being caused by user builds or the Bionic changes.

**Comment by thestinger** [comment]
The non-Firefox issues might be fixed in the upcoming release in a few hours. Firefox issues are still there and need to be narrowed down.

**Comment by polyzen** [comment]
@vanitasvitae, K-9 works fine here

@thestinger could there be a bigger issue with permissions than #104? The storage permission for Spotify had to also be manually set.

**Comment by thestinger** [comment]
> The storage permission for Spotify also had to be manually set.

Doubt it. CopperheadOS doesn't change any of that. Lots of apps have problems with the dynamic permissions in Android 6.0. The Google Play exceptions are certainly not a bug.

**Comment by thestinger** [comment]
I think the Chromium/WebView issue is caused by overly aggressive dynamic fortify changes introduced recently and if that's the case then it's fixed now. The Firefox problem is unrelated and is likely related to the problems from before. It's probably caused by OpenBSD malloc but it's not clear how.

**Comment by vanitasvitae** [comment]
@polyzen I changed some permissions, but I changed them back to check, if this causes the crashes. Still crashes. I found that there is a subcategory in the permissions concerning email stuff (reading attachements and so on) and K-9 is disabled in all of these categories. When I switch the on and go a level up and click the permission again, K-9 is disabled again. May that cause K9 to crash?

PS: Also I realized that photos that I take are not saved to memory. This affects Camera as well as Focal. Permissions aren't touched and seem to be right here. Should we open a new Issue for this or is this related?

**Comment by thestinger** [comment]
Please try the latest release first. It should fix the WebView/Chromium issues at the very least.

**Comment by thestinger** [comment]
There's a new release but it's still problematic. I don't need new bug reports just yet. I need to fix the existing problems which is taking quite some time, and those may be the causes of other problems.

Applications crashing due to handling the Android 6.0 dynamic permissions poorly isn't a bug though. It's not a CopperheadOS feature.

**Comment by thestinger** [comment]
Should have the Chromium issue fixed by the end of tomorrow.

**Comment by thestinger** [comment]
One of the Firefox compatibility issues has been fixed so it now works in userdebug builds. It doesn't yet work in user builds so it won't work with the published releases. It seems like it must be something like a missing SELinux rule.

**Comment by vanitasvitae** [comment]
Okay. I appreciate your hard work on this project. Btw, Android IMSI Catcher Detector also crashes with and without PaX-softmode enabled. Didn't want to open a new issue since you said you don't need new bug reports just yet :)

**Comment by thestinger** [comment]
I think the user build SELinux rules are too strict and it could be the same issue across most of these applications. I've found a few issues with user builds so far but it's important to get it working. It seems that AOSP is only really used for eng and userdebug builds.

**Comment by vanitasvitae** [comment]
Btw: Are there any plans to root the ROM by default (like in the CM-builds?) Tried to do root my device from within, but then I end up in a bootloop :/

**Comment by thestinger** [comment]
The main release will be unrooted to avoid the attack surface of a root implementation. CyanogenMod's implementation was found to be quite insecure and while the obvious issues are now fixed it is still a liability. There can be an alternative channel with root and more debugging support down the road when the project has more resources.

**Comment by polyzen** [comment]
@vanitasvitae, [this](
http://forum.xda-developers.com/android/software-hacking/wip-selinux-capable-superuser-t3216394)
worked for me. Used the update.zip format

**Comment by vanitasvitae** [comment]
@polyzen Nice, it worked for me too. Thanks :+1:

**Comment by thestinger** [comment]
Fully narrowed down the Firefox issue and have a solution that should work.
Finally narrowed down the remaining issue. Firefox breaks with PR_SET_DUMPABLE == 0 (which is the case in user builds) and hidepid=2, but not either alone. It crashes because it doesn't have proper error handling and that makes the problem seem a lot worse than it really turned out to be.

Part A: https://github.com/CopperheadOS/kernel_lge_hammerhead/commit/18b4a32dcaf788cceb482b96161045b553e1ae3b (was missing in PaX upstream, going to be fixed there too)
Part B: https://github.com/CopperheadOS/kernel_lge_hammerhead/commit/5275290bc83b37b33a09080b4fd54f6a8fc6cab7 (a backport to both the 3.4 and 3.10 Android kernels)

**Comment by thestinger** [comment]
Going to be fixed in the next release later today.

**Comment by polyzen** [comment]
fuckyeah.gif

**Comment by polyzen** [comment]
@vanitasvitae, sorry, did not respond to your earlier message.

> I found that there is a subcategory in the permissions concerning email stuff (reading attachements and so on) and K-9 is disabled in all of these categories. When I switch the on and go a level up and click the permission again, K-9 is disabled again. May that cause K9 to crash?

The permissions were the same here; haven't had to change them. It's been functional; can't recall if it's crashed..

> PS: Also I realized that photos that I take are not saved to memory. This affects Camera as well as Focal. Permissions aren't touched and seem to be right here. Should we open a new Issue for this or is this related?

Haven't had trouble here, either. I'm on hammerhead-ota_update-2015.12.18.13.08.17.zip

**Comment by thestinger** [comment]
The new release is uploaded for the Nexus 9 and will be uploaded for the Nexus 5 soon.

**Comment by thestinger** [comment]
The Nexus 5 release is out now.

**Comment by polyzen** [comment]
:+1: 

Note: Updating doesn't keep gapps and su installations intact. You will have to reinstall them directly after updating (before booting). Install opengapps last due to [this](opengapps/opengapps#201)

**Comment by vanitasvitae** [comment]
Unfortunately the update 2015.12.23 does not fix this issue for me. 
I still cannot take pictures and any app that shows html content crashes :/ 
I will try 2015.12.24, to see, if the crashes disappear.

**Comment by thestinger** [comment]
This bug tracks the Firefox issue, not the other issues. I haven't done anything about the other issues yet.

**Comment by thestinger** [comment]
https://github.com/copperhead/bugtracker/issues/112 is the next issue that's going to be worked on and it may be what you're running into.

**Comment by vanitasvitae** [comment]
Ah okay, sorry. Orfox also still crashes on my device (2015-12-23).

**Comment by thestinger** [comment]
I'm aware that there are general stability issues but that's not related to the issues here. If it ever works for you, then you aren't running into this (and I know you're not because it's fixed).

**Comment by vanitasvitae** [comment]
Okay thank you :+1: Let me know if I can help with logs or something. I'd really like to help in some way.

**Comment by thestinger** [comment]
https://github.com/copperhead/bugtracker/issues/112 tracks whatever is causing the inconsistent access errors. I think it's one bug across all the places where it's happening. It's probably an issue with one of the Bionic changes. There were some minor tweaks as part of the port of AOSP and one of those might have been wrong. It needs to be narrowed down by reverting Bionic changes, doing a clean build and then thoroughly testing to see if it fixes the problem. It's very time consuming so that's why it takes a while to fix these issues despite days of work.
